dependencies:
  # -<organization/repo>@<version>
  - aave/protocol-v2@1.0.1
  #- smartcontractkit/chainlink@0.10.14
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
      #- '@chainlink=smartcontractkit/chainlink@0.10.14'
networks:
  default: "mainnet-fork-dev"
  kovan:
    weth_token: '0x5eca15b12d959dfcf9c71c59f8b467eb8c6efd0b'
    lending_pool_addresses_provider: '0x88757f2f99175387aB4C6a4b3067c77A695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'

  mainnet-fork-dev:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    lending_pool_addresses_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    dai_token: '0x6b175474e89094c44da98b954eedeac495271d0f'
    dai_eth_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'

wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env